[feat] Location Module UseCase 정의
DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO pull request #58
Opened 2024-11-11 14:51 UTC by leeymin130

## 🔴 변경 사항 (What)
- `LocationUseCase` 설계
- `MapDisplayable` 인터페이스 설계
- `Bike`와 `Hub` Entity의 `MapDisplayable` 채택

## 🟠 변경 이유 (Why)
- `LocationUseCase`: 지도 화면에서 사용자가 수행해야하는 일들에 대한 목록을 먼저 설계하는 작업이 필요합니다. 각 로직을 함수로 분리하고, 필요한 데이터는 Repository를 통해 가져옵니다.
   - `fetchHubLocations()`: 허브 위치와 대여 가능 자전거 수를 반환
   - `fetchStations()`: 특정 허브의 스테이션 리스트를 반환
   - `fetchBikeLocation()`: 특정 자전거 위치를 반환

- `MapDisplayable`: 지도에 표시할 아이템에 필요한 공통 속성을 정의하기 위한 인터페이스를 정의합니다.

## 🟡 테스트 방법 (How to Test)

## 🔵 스크린샷 (Visual Proof) (Optional)

## 🟢 추가 노트 (Additional Notes)
- **Bike** 와 **Hub Entity**가 `MapDisplayable`을 채택하는 과정에서 **Location Entity**를 삭제하고 위치 표시를 위해 `coordinate` 속성을 사용하였습니다.

2024-11-11 15:05 UTC, OneMoreThink requested changes
제공된 서버 응답을 구조를 가지고 엔티티 및 유즈케이스에 대한 재구성이 필요해 보입니다.🥺

2024-11-13 01:21 UTC, OneMoreThink commented on Domado/Location/Sources/Location/Data/LocationRepository.swift
Repository에서 Datasource를 사용해서 서버로부터 데이터를 Fetch해올 때 Core 모듈에 정의된 Network 부분을 참고 하세용.

2024-11-13 01:22 UTC, OneMoreThink commented on Domado/Location/Sources/Location/Domain/LocationEntities/Bike.swift
> +    public let isAvailable: Bool
서버에서는 현재 이용가능한 자전거 목록만 응답으로 나갑니다. 
`isAvailable` 프로퍼티는 왜 필요할까요?

2024-11-13 01:32 UTC, OneMoreThink commented on Domado/Location/Sources/Location/Domain/LocationEntities/Station.swift
> +    public var availableBikes: Int {
각 허브에는 현재 주차되어 있는 자전거 (대여 가능한 자전거) 만 응답으로 나가기 때문에 요청에 대한 자전거들은 모두 대여 가능한 상태입니다.

2024-11-13 01:32 UTC, OneMoreThink commented on Domado/Location/Sources/Location/Domain/LocationEntities/Hub.swift
> +    public var title: String {
`hubName`을 직접 사용하지 않고 별도의 저장 프로퍼티를 놓은 이유가 뭘까요? 해당 변수를 이용하는 곳에 맞는 변수명을 제공하기 위함인가요?

2024-11-13 01:32 UTC, OneMoreThink commented on Domado/Location/Sources/Location/Domain/MapDisplayable.swift
> +public enum MarkerType {
MarkerType 과 연관값이 어떠한 용도로 사용될지에 대한 설명이 필요합니다.

2024-11-13 05:05 UTC, leeymin130 commented on Domado/Location/Sources/Location/Domain/LocationEntities/Station.swift
> +    public var availableBikes: Int {
허브를 표시하는 마커에 대여 가능한 자전거의 대수가 함께 표시되어야하기 때문에 프로퍼티로 넣었습니다!

2024-11-13 07:23 UTC, leeymin130 commented on Domado/Location/Sources/Location/Domain/MapDisplayable.swift
> +public enum MarkerType {
MarkerType는 지도 위에 위치를 마커로 표시할 때 허브와 HiBike를 구분해서 표시하기 위해 사용됩니다. betteryLevel을 필요가 없을 것 같네요. 수정하겠습니다.

2024-11-13 07:33 UTC, leeymin130 commented on Domado/Location/Sources/Location/Domain/LocationEntities/Hub.swift
> +    public var title: String {
지도나 UI에 표시될 허브 이름을 위한 속성인데, hubName을 사용하는 게 좋을 것 같습니다. 삭제하겠습니다.

2024-11-13 07:59 UTC, leeymin130 commented on Domado/Location/Sources/Location/Domain/LocationEntities/Bike.swift
> +    public let isAvailable: Bool
이해 완! 필요 없는 것 같아 삭제하겠습니다.

2024-11-13 14:30 UTC, OneMoreThink approved these changes
수정사항 잘 반영된 것 같습니다. 다음 단계에는 정의한 엔티티를 바탕으로 각 데이터를 화면에 표시하기 위해 구성하는 단계로 가봅시다. 🌻

2024-11-13 15:29 UTC, merged